development:
  insurance_api: https://bab203fd-d999-4b90-9570-6aa9c2a5ae31.mock.pstmn.io/api/v1
  payment_options_api: https://mocki.io/v1/f914b988-2ce9-4263-bca2-dd40fd3a20ba

test:
  insurances_api: http://localhost:4000/api/v1
  payment_options_api: http://localhost:4000/api/v1
